/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _PARIDAD_RPC_H_RPCGEN
#define _PARIDAD_RPC_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif


#define PARIDAD_PROG 0x20000001
#define PARIDAD_V1 1

#if defined(__STDC__) || defined(__cplusplus)
#define es_par_impar 1
extern  char ** es_par_impar_1(int *, CLIENT *);
extern  char ** es_par_impar_1_svc(int *, struct svc_req *);
extern int paridad_prog_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define es_par_impar 1
extern  char ** es_par_impar_1();
extern  char ** es_par_impar_1_svc();
extern int paridad_prog_1_freeresult ();
#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_PARIDAD_RPC_H_RPCGEN */
